version: '3'
services:
  app:
    build: .
    command: /app/docker/entry start-dev
    volumes:
      - ./data/projects:/app/data/projects:rw
      - ./portiaui/dist:/app/portiaui/dist
      - ./slyd:/app/slyd
      - ./portia_server:/app/portia_server
      - ./slybot:/app/slybot
    ports:
      - 9001:9001
    restart: always
